### ISSUE TITLE
how to setup ?

### ISSUE THREAD

**Issue by mindjek07** [FriedPigeon/gallery-php#10]
how to setup ?

**Comment by FriedPigeon** [comment]
There’s nothing out of the ordinary about this PHP project regarding setup. If you are familiar with MySQL and PHP then simply configurating MySQL with the database and tables described in the README and check the `mysqli_connect` parameters in the Database class constructor, and placing the project files in the index of a PHP web server, should be enough to have it running.
If you are unfamiliar with MySQL and/or PHP then a good place to start is with XAMPP, as it makes setting up easy for beginners. There are many tutorials on the internet about web development with MySQL and PHP, particularly for XAMPP.
